version: '3'

services:
  swagchat-chat-api:
    image: swagchat/chat-api
    links:
      - swagchat-rtm-api
      - mysql-master
      - nsqd
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./storage:/tmp/storage
    environment:
      SC_DEMO_PAGE: "true"
      SC_DATASTORE_PROVIDER: mysql
      SC_DATASTORE_TABLE_NAME_PREFIX: sc_
      SC_DATASTORE_USER: swagchat
      SC_DATASTORE_PASSWORD: password
      SC_DATASTORE_DATABASE: swagchat
      SC_DATASTORE_MASTER_HOST: mysql-master
      SC_DATASTORE_MASTER_PORT: 3306
      SC_STORAGE_PROVIDER: local
      SC_STORAGE_BASE_URL: http://localhost:9000/v0/assets
      SC_STORAGE_LOCAL_PATH: /tmp/storage/
      SC_RTM_PROVIDER: nsq
      SC_RTM_QUE_ENDPOINT: http://nsqd:4151
      SC_RTM_QUE_TOPIC: websocket
      SC_REACT_CHAT_ENDPOINT: /v0
      SC_REACT_RTM_PROTOCOL: ws
      SC_REACT_RTM_HOST: 127.0.0.1:9100
      SC_REACT_RTM_PATH: /v0
    networks:
      - swagchat
  swagchat-rtm-api:
    image: swagchat/rtm-api
    links:
      - nsqlookupd
      - nsqd
    restart: always
    command: swagchat-rtm-api -nsqlookupdHost nsqlookupd -nsqdHost nsqd
    ports:
      - "9100:9100"
    networks:
      - swagchat
  mysql-master:
    image: mysql:5.7.17
    restart: always
    ports:
      - 3306:3306
    networks:
      - swagchat
    volumes:
      - ./datastore/mysql-master/var/lib/mysql:/var/lib/mysql
      - ./datastore/mysql-master/var/log:/var/log
      - ./datastore/mysql-master/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: master_password
      MYSQL_DATABASE: swagchat
      MYSQL_USER: swagchat
      MYSQL_PASSWORD: password
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
    networks:
      - swagchat
  nsqd:
    image: nsqio/nsq
    links:
      - nsqlookupd
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 -config /config/nsqd.cfg
    ports:
      - "4150:4150"
      - "4151:4151"
    volumes:
      - ./rtm/var/lib/nsq:/var/lib/nsq
      - ./rtm/config:/config
    networks:
      - swagchat
  nsqadmin:
    image: nsqio/nsq
    links:
      - nsqlookupd
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    ports:
      - "4171:4171"
    networks:
      - swagchat
networks:
  swagchat:
    driver: bridge
